name: Update data

on: 
  schedule:  
    - cron:  '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages("remotes", repos="http://cran.rstudio.com")
          install.packages('highcharter', dependencies = TRUE)
          install.packages('XML', dependencies = TRUE)
          install.packages('rlist', dependencies = TRUE)
          install.packages('rlang', dependencies = TRUE)
          remotes::install_version(package = "tidyverse", version = "1.3.1", dependencies = TRUE)
          remotes::install_version(package = "lubridate", version = "1.7.10", dependencies = TRUE)
          remotes::install_version(package = "rsconnect", version = "0.8.25", dependencies = TRUE)
          remotes::install_version(package = "shinyFeedback", version = "0.4.0", dependencies = TRUE)
          remotes::install_version(package = "glue", version = "1.4.2", dependencies = TRUE)
          remotes::install_version(package = "shinydashboard", version = "0.7.2", dependencies = TRUE)
          remotes::install_version(package = "writexl", version = "1.4.0", dependencies = TRUE)
          remotes::install_version(package = "httr", version = "1.4.2", dependencies = TRUE)
          remotes::install_version(package = "cpp11", version = "0.4.1", dependencies = TRUE)
          remotes::install_version(package = "dplyr", version = "1.0.7", dependencies = TRUE)
          remotes::install_version(package = "tidyr", version = "1.2.0", dependencies = TRUE)
          remotes::install_version(package = "readxl", version = "1.4.0", dependencies = TRUE)


        shell: Rscript {0}
        
#      - name: Update data
#       run: |
#         source("update_data.R")
#       shell: Rscript {0}

        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 